services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=dutyduck
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - dutyduck-database:/var/lib/postgresql/data 
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8081:8080
  mailserver:
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:24.0.4
    ports:
      - 8080:8080
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://database:5432/dutyduck"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

volumes:
  dutyduck-database: {}