version: '3'
services:
  dev-container:
    depends_on: []
      # - fake-internet
    image: mcr.microsoft.com/devcontainers/base:bullseye
    command: ["sleep", "infinity"]
    ports:
      - 5173:5173
      - 3000:3000
    volumes:
      - .:/home/workspace:cached

  # fake-internet:
  #   build: ./fake-internet
  #   environment:
  #     - PORT=80
  #   networks:
  #     default:
  #       aliases:
  #         - www.mediapart.fr
  #         - www.fake-internet.com

  main-database:
    build: ./database
    environment:
      - POSTGRES_DB=dutyduck
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - main-database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  keycloak-database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - keycloak-database:/var/lib/postgresql/data
    ports:
      - 5433:5432

  mailserver:
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:24.0.4
    ports:
      - 8080:8080
    command:
      [
        "start-dev",
        --spi-email-template-provider=freemarker-plus-mustache,
        --spi-email-template-freemarker-plus-mustache-enabled=true,
      ]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://keycloak-database:5432/keycloak"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_LOG_LEVEL: DEBUG

volumes:
  main-database: {}
  keycloak-database: {}
