version: '3'
services:
  dev-container:
    depends_on:
      - fake-internet
    image: mcr.microsoft.com/devcontainers/base:bullseye
    command: ["sleep", "infinity"]
    ports:
      - 5173:5173
      - 3000:3000
    volumes:
      - .:/home/workspace:cached

  fake-internet:
    build: ./fake-internet
    environment:
      - PORT=80
    networks:
      default:
        aliases:
          - www.mediapart.fr
          - www.fake-internet.com
  database:
    build: ./database
    environment:
      - POSTGRES_DB=dutyduck
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - dutyduck-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8081:8080
  mailserver:
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:24.0.4
    ports:
      - 8080:8080
    command:
      [
        "start-dev",
        --spi-email-template-provider=freemarker-plus-mustache,
        --spi-email-template-freemarker-plus-mustache-enabled=true,
      ]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://database:5432/dutyduck"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_LOG_LEVEL: DEBUG

volumes:
  dutyduck-database: {}