[package]
name = "api-client-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
uuid.workspace = true
chrono.workspace = true