[package]
name = "ingestor"
edition = "2021"
build = "build.rs"
publish = false

[dependencies]
dutyduck-api-client-rs.workspace = true
quickwit-client-rs.workspace = true

axum.workspace = true
futures.workspace = true
futures-util.workspace = true
anyhow.workspace = true
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
clap.workspace = true
envconfig.workspace = true
dotenv.workspace = true
tonic.workspace = true
moka.workspace = true
uuid.workspace = true
opentelemetry-proto.workspace = true

crc32fast = "1.4.2"
hex = "0.4.3"

[build-dependencies]
built = { version = "0.7.3", features = ["chrono", "git2"] }
