steps:
  - id: Build
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=$_AR_HOSTNAME/$PROJECT_ID/duty-duck/browser:$COMMIT_SHA
      - --dockerfile=components/browser/Dockerfile
      - --context=.
      - --cache=true
      - --cache-ttl=120h
      - --cache-repo=$_AR_HOSTNAME/$PROJECT_ID/duty-duck/browser/cache

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Hostname of the artifact registry
  _AR_HOSTNAME: europe-west1-docker.pkg.dev