use super::*;

/// The doc mapping of indices to store OTEL Logs, adapted from [Quickwit's documentation](https://quickwit.io/docs/log-management/otel-service#opentelemetry-logs-data-model)
/// and derived from ÓTEL's data model
pub fn otel_logs_doc_mapping() -> DocMapping {
    DocMapping {
        mode: DocMappingMode::Strict,
        partition_key: None,
        max_num_partitions: None,
        tag_fields: None,
        store_source: false,
        timestamp_field: Some("timestamp_nanos".to_string()),
        field_mappings: vec![
            FieldMapping::DateTime(DateTimeFieldMapping {
                name: "timestamp_nanos".to_string(),
                description: None,
                input_formats: Some(vec!["unix_timestamp".to_string()]),
                output_format: Some("unix_timestamp_nanos".to_string()),
                indexed: false,
                fast: true,
                fast_precision: Some(DateTimeFastPrecision::MilliSeconds),
                stored: true,
            }),
            FieldMapping::DateTime(DateTimeFieldMapping {
                name: "observed_timestamp_nanos".to_string(),
                description: None,
                input_formats: Some(vec!["unix_timestamp".to_string()]),
                output_format: Some("unix_timestamp_nanos".to_string()),
                indexed: true,
                stored: true,
                fast: false,
                fast_precision: None,
            }),
            FieldMapping::Text(TextFieldMapping {
                name: "severity_text".to_string(),
                description: None,
                stored: true,
                indexed: true,
                tokenizer: Some("raw".to_string()),
                record: None,
                fieldnorms: false,
                fast: true,
            }),
            FieldMapping::Unsigned64(NumericFieldMapping {
                name: "severity_number".to_string(),
                description: None,
                stored: true,
                indexed: true,
                fast: true,
                coerce: true,
            }),
            FieldMapping::Json(JsonFieldMapping {
                name: "body".to_string(),
                description: None,
                stored: true,
                indexed: true,
                fast: false,
                tokenizer: Some("default".to_string()),
                record: Some(Record::Position),
                expand_dots: true,
            }),
            FieldMapping::Unsigned64(NumericFieldMapping {
                name: "dropped_attributes_count".to_string(),
                description: None,
                stored: true,
                indexed: false,
                fast: false,
                coerce: true,
            }),
            FieldMapping::Bytes(BytesFieldMapping {
                name: "trace_id".to_string(),
                description: None,
                stored: true,
                indexed: true,
                fast: true,
                input_format: BytesEncoding::Hex,
                output_format: BytesEncoding::Hex,
            }),
            FieldMapping::Bytes(BytesFieldMapping {
                name: "span_id".to_string(),
                description: None,
                stored: true,
                indexed: true,
                fast: true,
                input_format: BytesEncoding::Hex,
                output_format: BytesEncoding::Hex,
            }),
            FieldMapping::Unsigned64(NumericFieldMapping {
                name: "trace_flags".to_string(),
                description: None,
                stored: true,
                indexed: false,
                fast: false,
                coerce: true,
            }),
            FieldMapping::Json(JsonFieldMapping {
                name: "resource_attributes".to_string(),
                description: None,
                stored: true,
                indexed: true,
                fast: true,
                tokenizer: Some("raw".to_string()),
                record: Some(Record::Basic),
                expand_dots: true,
            }),
            FieldMapping::Unsigned64(NumericFieldMapping {
                name: "resource_dropped_attributes_count".to_string(),
                description: None,
                stored: true,
                indexed: false,
                fast: false,
                coerce: true,
            }),
            FieldMapping::Text(TextFieldMapping {
                name: "scope_name".to_string(),
                description: None,
                indexed: false,
                stored: true,
                fast: false,
                tokenizer: None,
                fieldnorms: false,
                record: None,
            }),
            FieldMapping::Text(TextFieldMapping {
                name: "scope_version".to_string(),
                description: None,
                indexed: false,
                stored: true,
                fast: false,
                tokenizer: None,
                fieldnorms: false,
                record: None,
            }),
            FieldMapping::Json(JsonFieldMapping {
                name: "scope_attributes".to_string(),
                description: None,
                stored: true,
                indexed: false,
                fast: false,
                tokenizer: None,
                record: None,
                expand_dots: true,
            }),
            FieldMapping::Unsigned64(NumericFieldMapping {
                name: "scope_dropped_attributes_count".to_string(),
                description: None,
                stored: true,
                indexed: false,
                fast: false,
                coerce: true,
            }),
            FieldMapping::Json(JsonFieldMapping {
                name: "attributes".to_string(),
                description: None,
                stored: true,
                indexed: false,
                fast: false,
                tokenizer: None,
                record: None,
                expand_dots: true,
            }),
        ],
    }
}
