// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateHttpMonitorCommand = { url: string, intervalSeconds: number, recoveryConfirmationThreshold: number, downtimeConfirmationThreshold: number, isActive: boolean, tags: Array<string>, };
