// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Key-value pairs of data that can be attached to monitors, incidents, etc. to add context
 * and filter entities
 */
export type EntityMetadata = { records: { [key in string]?: string }, };
