// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterableMetadataValue } from "./FilterableMetadataValue";

export type FilterableMetadataItem = { key: string, distinct_values: Array<FilterableMetadataValue>, key_cardinality: bigint, };
