// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorErrorKind } from "./HttpMonitorErrorKind";
import type { HttpMonitorStatus } from "./HttpMonitorStatus";

export type HttpMonitor = { organizationId: string, id: string, createdAt: string, url: string, firstPingAt: string | null, nextPingAt: string | null, lastPingAt: string | null, intervalSeconds: bigint, lastHttpCode: number | null, status: HttpMonitorStatus, statusCounter: number, errorKind: HttpMonitorErrorKind, tags: Array<string>, };
