// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorIncidentCause } from "./HttpMonitorIncidentCause";

/**
 * An enum that represents the cause of an incident
 */
export type IncidentCause = { "causeType": "HttpMonitorIncidentCause", lastPing: HttpMonitorIncidentCause, previousPings: Array<HttpMonitorIncidentCause>, };
