// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorErrorKind } from "./HttpMonitorErrorKind";

/**
 * An enum that represents the cause of an incident
 */
export type IncidentCause = { "causeType": "HttpMonitorIncidentCause", errorKind: HttpMonitorErrorKind, httpCode: number | null, };
