// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcknowledgedEventPayload } from "./AcknowledgedEventPayload";
import type { CommentPayload } from "./CommentPayload";
import type { NotificationEventPayload } from "./NotificationEventPayload";
import type { PingEventPayload } from "./PingEventPayload";

export type IncidentEventPayload = { "Comment": CommentPayload } | { "Notification": NotificationEventPayload } | { "Acknowledged": AcknowledgedEventPayload } | { "Ping": PingEventPayload };
