// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Incident } from "./Incident";

export type ListIncidentsResponse = { items: Array<Incident>, totalNumberOfResults: number, totalNumberOfFilteredResults: number, };
