// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitor } from "./HttpMonitor";

export type ListHttpMonitorsResponse = { items: Array<HttpMonitor>, totalNumberOfResults: number, };
