// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListOrganizationMembersItem } from "./ListOrganizationMembersItem";

export type ListOrganizationMembersResponse = { members: Array<ListOrganizationMembersItem>, };
