// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorStatus } from "./HttpMonitorStatus";

export type ListHttpMonitorsParams = { pageNumber: number | null, itemsPerPage: number | null, include: Array<HttpMonitorStatus> | null, query: string | null, };
