// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IncidentPriority } from "./IncidentPriority";
import type { IncidentStatus } from "./IncidentStatus";

export type ListIncidentsParams = { pageNumber: number | null, itemsPerPage: number | null, status: Array<IncidentStatus> | null, priority: Array<IncidentPriority> | null, };
