// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationUserRole } from "./OrganizationUserRole";

export type ListOrganizationMembersItem = { organizationRoles: Array<OrganizationUserRole>, id: string, firstName: string, lastName: string, email: string, phoneNumber: string | null, };
