// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An object used to filter database entities by metadata
 * It will match all rows if no filters are provided, otherwise,
 * it will match rows that have all the provided records, and for each record,
 * it will match rows that have any of the provided values
 */
export type MetadataFilter = { items: { [key in string]?: Array<string> }, };
