// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PushNotificationToken } from "./PushNotificationToken";

/**
 * A rapper arround an optional [PushNotificationToken], required to query the database using the `sqlx::query_as!` macro.
 */
export type OptionalPushNotificationToken = PushNotificationToken | null;
