// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";

export type Organization = { id: string, name: string, displayName: string, stripeCustomerId: string | null, billingAddress: Address | null, createdAt: string, updatedAt: string, };
