// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrganizationUserRole = "Reporter" | "Editor" | "MemberInviter" | "MemberManager" | "Administrator" | "Owner";
