// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorErrorKind } from "./HttpMonitorErrorKind";

export type PingEventPayload = { httpCode: number | null, errorKind: HttpMonitorErrorKind, };
