// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorErrorKind } from "./HttpMonitorErrorKind";

export type PingEventPayload = { httpCode: number | null, errorKind: HttpMonitorErrorKind, httpHeaders: { [key in string]?: string }, responseTimeMs: bigint, responseIpAddress: string | null, resolvedIpAddresses: Array<string>, };
