// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitor } from "./HttpMonitor";
import type { IncidentWithSources } from "./IncidentWithSources";

export type ReadHttpMonitorResponse = { monitor: HttpMonitor, ongoingIncident: IncidentWithSources | null, };
