// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProfileCommand = { first_name: string | null, last_name: string | null, email: string | null, password: string | null, phone_number: string | null, };
