// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateHttpMonitorCommand = { url: string, intervalSeconds: number, isActive: boolean, tags: Array<string>, recoveryConfirmationThreshold: number, downtimeConfirmationThreshold: number, };
