// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type UpdateProfileResponse = { needs_session_invalidation: boolean, new_user: User, };
