// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserDeviceType } from "./UserDeviceType";

export type UserDevice = { organizationId: string, userId: string, id: string, createdAt: string, label: string, pushNotificationToken: string | null, deviceType: UserDeviceType, };
