steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_AR_HOSTNAME/$PROJECT_ID/duty-duck/frontend:$COMMIT_SHA
      - '-f'
      - components/frontend/Dockerfile
      - .

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/duty-duck/frontend:$COMMIT_SHA

images:
  - $_AR_HOSTNAME/$PROJECT_ID/duty-duck/frontend:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Hostname of the artifact registry
  _AR_HOSTNAME: europe-west1-docker.pkg.dev