name: CLI Release
on:
  push:
    tags:
      - "cli/v*.*.*"
    paths:
      - "components/cli/**"
jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.runner }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            runner: ubicloud-standard-2
            target: x86_64-unknown-linux-gnu
            bin_name: dutyduck
          - name: linux-arm64
            runner: ubicloud-standard-2-arm
            target: aarch64-unknown-linux-gnu
            bin_name: dutyduck
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
            bin_name: dutyduck
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            bin_name: dutyduck
          - name: windows-amd64
            runner: windows-latest
            target: x86_64-pc-windows-gnu
            bin_name: dutyduck.exe
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
      
      - name: Build CLI binary
        run: cargo build -p dutyduck_cli --bin dutyduck --release --locked --target ${{ matrix.target }} --verbose

      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/${{ matrix.bin_name }} target/${{ matrix.target }}/release/${{ matrix.name }}-${{ matrix.bin_name }}

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:  target/${{ matrix.target }}/release/${{ matrix.name }}-${{ matrix.bin_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          body: |
            This is a release of the DutyDuck CLI, version ${{ github.ref_name }}.
            For more information, please visit the [DutyDuck website](https://dutyduck.net).

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload to S3
        run: |
          aws s3 cp target/${{ matrix.target }}/release/${{ matrix.name }}-${{ matrix.bin_name }} s3://dutyduck-releases/${{ github.ref_name }}/${{ matrix.name }}-${{ matrix.bin_name }}

