name: Database Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "database/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: database
        push: true
        tags: duty-duck-postgres:$(date +%s)
