name: fake-internet image CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "fake-internet/**"
  push:
    paths:
      - "fake-internet/**"
jobs:
  build:
    runs-on: ubicloud-standard-4-arm
    permissions:
      contents: read
      packages: write

    steps:
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/duty-duck/fake-internet
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=sha

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        context: .
        file: "components/fake-internet/Dockerfile"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
