// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Address = { line1: string, line2: string, city: string, stateOrProvince: string, postalCode: string, updatedAt: string, updatedByUserId: string, };
