// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMetadata } from "./EntityMetadata";

/**
 * A command to create a new task
 */
export type CreateTaskCommand = { 
/**
 * A unique, human-readable identifier for the task
 */
id: string, 
/**
 * A human-readable name for the task
 */
name: string | null, 
/**
 * A description of the task
 */
description: string | null, 
/**
 * A cron schedule for the task, to make it a scheduled task
 */
cronSchedule: string | null, 
/**
 * A timezone for the task, if this is a scheduled task
 * Defaults to UTC
 */
scheduleTimezone: string | null, 
/**
 * A number of seconds to wait, once this scheduled task is due, before the task is considered late
 */
startWindowSeconds: number | null, 
/**
 * A number of seconds to wait, once this scheduled task is late, before the task is considered failed
 */
latenessWindowSeconds: number | null, 
/**
 * A number of seconds to wait, after the last heartbeat was received, if any, before the task is considered failed
 */
heartbeatTimeoutSeconds: number | null, metadata: EntityMetadata | null, 
/**
 * Whether to send an email notification when an incident occurs for this task
 * Defaults to true
 */
emailNotificationEnabled: boolean | null, 
/**
 * Whether to send a push notification when an incident occurs for this task
 * Defaults to true
 */
pushNotificationEnabled: boolean | null, 
/**
 * Whether to send a SMS notification when an incident occurs for this task
 * Defaults to false
 */
smsNotificationEnabled: boolean | null, };
