// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMetadata } from "./EntityMetadata";

export type CreateTaskCommand = { id: string, name: string | null, description: string | null, cronSchedule: string | null, scheduleTimezone: string | null, startWindowSeconds: number | null, latenessWindowSeconds: number | null, heartbeatTimeoutSeconds: number | null, metadata: EntityMetadata | null, };
