// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTaskCommand = { id: string, name: string, description: string | null, isActive: boolean, cronSchedule: string | null, startWindowSeconds: number, latenessWindowSeconds: number, heartbeatTimeoutSeconds: number, };
