// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterableMetadataItem } from "./FilterableMetadataItem";

export type FilterableMetadata = { items: Array<FilterableMetadataItem>, };
