// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishedTaskStatus } from "./FinishedTaskStatus";

export type FinishTaskCommand = { status: FinishedTaskStatus, exitCode: number | null, errorMessage: string | null, };
