// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineItem } from "./TimelineItem";

export type GetIncidentTimelineResponse = { items: Array<TimelineItem>, };
