// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Organization } from "./Organization";
import type { OrganizationUserRole } from "./OrganizationUserRole";
import type { Permission } from "./Permission";
import type { User } from "./User";

export type GetProfileResponse = { user: User, permissions: Array<Permission>, active_organization: Organization, organization_roles: Array<OrganizationUserRole>, };
