// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexedTaskRunLogEvent } from "./IndexedTaskRunLogEvent";

export type GetTaskRunLogsResponse = { totalNumberOfLogs: bigint, logs: Array<IndexedTaskRunLogEvent>, };
