// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetTaskRunLogsParams = { 
/**
 * How many log records to retrieve at a time. The default value is 200, the maximum value is 500
 */
limit: number | null, offset: number | null, };
