// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpMonitorErrorKind = "unknown" | "none" | "httpcode" | "connect" | "builder" | "request" | "redirect" | "body" | "decode" | "timeout" | "browserservicecallfailed";
