// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IncidentSourceWithDetails = { "type": "HttpMonitor", id: string, url: string, email_notification_enabled: boolean, push_notification_enabled: boolean, sms_notification_enabled: boolean, };
