// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IncidentEventPayload } from "./IncidentEventPayload";
import type { IncidentEventType } from "./IncidentEventType";

/**
 * An event that is recorded for an incident.
 */
export type IncidentEvent = { organizationId: string, incidentId: string, userId: string | null, createdAt: string, eventType: IncidentEventType, eventPayload: IncidentEventPayload | null, };
