// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IncidentEventType = "creation" | "notification" | "resolution" | "comment" | "acknowledged" | "confirmation" | "monitorpinged" | "monitorswitchedtorecovering" | "monitorswitchedtosuspicious" | "monitorswitchedtodown" | "taskswitchedtodue" | "taskswitchedtolate" | "taskswitchedtoabsent" | "taskswitchedtorunning" | "taskrunstarted" | "taskrunisdead" | "taskrunfailed" | "taskrunreceivedlastheartbeat";
