// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitorIncidentCause } from "./HttpMonitorIncidentCause";
import type { ScheduledTaskIncidentCause } from "./ScheduledTaskIncidentCause";
import type { TaskRunIncidentCause } from "./TaskRunIncidentCause";

/**
 * An enum that represents the cause of an incident
 */
export type IncidentCause = { "causeType": "HttpMonitorIncidentCause" } & HttpMonitorIncidentCause | { "causeType": "ScheduledTaskIncidentCause" } & ScheduledTaskIncidentCause | { "causeType": "TaskRunIncidentCause" } & TaskRunIncidentCause;
