// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An enum the can hold one of the different incident types at runtime
 */
export type IncidentSource = { "type": "HttpMonitor", id: string, } | { "type": "Task", id: string, } | { "type": "TaskRun", id: string, };
