// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiAccessToken } from "./ApiAccessToken";

export type ListApiAccessTokensResponse = { apiTokens: Array<ApiAccessToken>, };
