// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type ListTasksParams = { include: Array<TaskStatus> | null, searchQuery: string, pageNumber: number | null, itemsPerPage: number | null, };
