// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskRunStatus } from "./TaskRunStatus";

export type ListTaskRunsParams = { includeStatuses: Array<TaskRunStatus> | null, pageNumber: number | null, itemsPerPage: number | null, };
