// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskRun } from "./TaskRun";

export type ListTaskRunsResponse = { runs: Array<TaskRun>, totalRuns: number, totalFilteredRuns: number, };
