// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An optional command that can be used to create a task on-the-fly when starting a task run
 */
export type NewTask = { 
/**
 * A human-readable name for the task
 */
name: string | null, 
/**
 * A description of the task
 */
description: string | null, 
/**
 * A cron schedule for the task, to make it a scheduled task
 */
cronSchedule: string | null, 
/**
 * A number of seconds to wait, once this scheduled task is due, before the task is considered late
 */
startWindowSeconds: number | null, 
/**
 * A number of seconds to wait, once this scheduled task is late, before the task is considered late
 */
latenessWindowSeconds: number | null, 
/**
 * A number of seconds to wait, after the last heartbeat was received, if any, before the task is considered failed
 */
heartbeatTimeoutSeconds: number | null, 
/**
 * The timezone to use for the task's schedule (defaults to UTC)
 */
scheduleTimezone: string | null, 
/**
 * Whether to send an email notification when an incident occurs for this task
 */
emailNotificationEnabled: boolean | null, 
/**
 * Whether to send a push notification when an incident occurs for this task
 */
pushNotificationEnabled: boolean | null, 
/**
 * Whether to send a SMS notification when an incident occurs for this task
 */
smsNotificationEnabled: boolean | null, };
