// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Permission = "transferOwnershipOfOrganization" | "inviteOrganizationMember" | "removeOrganizationMember" | "listOrganizationMembers" | "editOrganizationMember" | "removeOrganization" | "readHttpMonitors" | "writeHttpMonitors" | "readIncidents" | "listOrganizationInvitations" | "commentIncidents" | "editIncidents" | "writeTasks" | "readTasks" | "writeTaskRuns" | "readTaskRuns";
