// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uses by the push notification server to identify a device
 */
export type PushNotificationToken = string;
