// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMonitor } from "./HttpMonitor";
import type { Incident } from "./Incident";

export type ReadHttpMonitorResponse = { monitor: HttpMonitor, ongoingIncident: Incident | null, };
