// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Organization } from "./Organization";
import type { User } from "./User";
import type { UserInvitation } from "./UserInvitation";

export type ReceiveInvitationResponse = { 
/**
 * The invitation contains information about the invitee and the role they are invited to.
 */
invitation: UserInvitation, 
/**
 * The inviter is the user that invited the invitee to the organization.
 */
inviter: User, organization: Organization, 
/**
 * The invitee may or may not exist in the system, since users can belong to multiple organizations.
 */
invitee: User | null, };
