// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduledTaskIncidentCause = { taskId: string, taskUserId: string, taskWasDueAt: string, taskRanLateAt: string | null, taskSwitchedToAbsentAt: string | null, };
