// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewTask } from "./NewTask";

/**
 * An optional command that can be used to create a task on-the-fly when starting a task run
 */
export type StartTaskCommand = { 
/**
 * The properties of the new task to create if the task does not exist yet
 */
newTask: NewTask | null, 
/**
 * Whether to abort the previous running task
 */
abortPreviousRunningTask: boolean, };
