// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An enum that represents the status of a task run
 */
export type TaskStatus = "inactive" | "running" | "pending" | "due" | "late" | "absent" | "dead" | "aborted";
