// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMetadata } from "./EntityMetadata";
import type { TaskStatus } from "./TaskStatus";

export type Task = { 
/**
 * A random, unique identifier for the task.
 */
id: string, 
/**
 * A unique, user-friendly identifier for the task.
 */
userId: string, organizationId: string, name: string, description: string | null, status: TaskStatus, previousStatus: TaskStatus | null, lastStatusChangeAt: string | null, cronSchedule: string | null, scheduleTimezone: string | null, nextDueAt: string | null, startWindowSeconds: number, latenessWindowSeconds: number, heartbeatTimeoutSeconds: number, createdAt: string, metadata: EntityMetadata, };
