// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single log event from a task run. (By default, each new line in the standard output is considered a seperate event)
 * This type has a conversion from and to the OpenTelemetry format, which we can use to ingest task run logs and retrieve them back later
 */
export type TaskRunLogEvent = { 
/**
 * severity text (also known as log level). This is the original string representation of the severity as it is known at the source, for instance "DEBUG", or "ERROR".
 * This default behaviour of the DutyDuck CLI is to treat the standard output of the process as "INFO" and the standard error as "ERROR".
 */
severityText: string | null, 
/**
 * SeverityNumber is an integer number. Smaller numerical values correspond to less severe events (such as debug events), larger numerical values correspond to more severe events (such as errors and critical events).
 * The meaning of this value is defined by the OpenTelemetry standard.
 * This default behaviour of the DutyDuck CLI is to treat the standard output of the process as "INFO" (severity number = 9) and the standard error as "ERROR" (severity_number = 17).
 */
severityNumber: number | null, 
/**
 * The body of the log. This can be unstructured data (i.e. a string of text) or a structured map of keys and values
 * If structured data is desired, the client is responsible for supplying the structured data.
 * The default behaviour of the DutyDuck CLI is to capture the raw standard output and standard error streams of the process as unstructured data.
 */
body: any, 
/**
 * The timestamp at which the log occured, as measured by the orgin clock
 */
timestamp: string, };
