// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskRunStatus } from "./TaskRunStatus";

export type TaskRunIncidentCause = { taskId: string, taskRunId: string, taskRunStartedAt: string, taskRunFinishedAt: string | null, taskRunStatus: TaskRunStatus, };
