// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskRunStatus } from "./TaskRunStatus";

export type TaskRun = { organizationId: string, taskId: string, status: TaskRunStatus, startedAt: string, updatedAt: string, completedAt: string | null, exitCode: number | null, errorMessage: string | null, lastHeartbeatAt: string | null, };
