// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IncidentEvent } from "./IncidentEvent";
import type { TimelineItemUser } from "./TimelineItemUser";

export type TimelineItem = { event: IncidentEvent, user: TimelineItemUser | null, };
