// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMetadata } from "./EntityMetadata";

export type UpdateTaskCommand = { 
/**
 * A unique, user-friendly identifier for the task.
 * Will keep the id of the existing task if null
 */
userId: string, 
/**
 * The name of the task.
 * Will keep the name of the existing task if null
 */
name: string | null, 
/**
 * A description of the task.
 * Will remove the description of the existing task if null
 */
description: string | null, 
/**
 * A cron schedule for the task, to make it a scheduled task
 * Will erase the cron_schedule of the exisint task if null
 */
cronSchedule: string | null, 
/**
 * A timezone for the task, if this is a scheduled task
 * Will reset the timezone to UTC if null
 */
scheduleTimezone: string | null, 
/**
 * A number of seconds to wait, once this scheduled task is due, before the task is considered late
 * Will reset to the default value if null
 */
startWindowSeconds: number | null, 
/**
 * A number of seconds to wait, once this scheduled task is late, before the task is considered failed
 * Will reset to the default value if null
 */
latenessWindowSeconds: number | null, 
/**
 * A number of seconds to wait, after the last heartbeat was received, if any, before the task is considered failed
 * Will reset to the default value if null
 */
heartbeatTimeoutSeconds: number | null, 
/**
 * Metadata used to organize and filter tasks
 * Will keep the metadata of the existing task if null
 */
metadata: EntityMetadata | null, 
/**
 * Whether to send an email notification when an incident occurs for this task
 * Will keep the existing value if null
 */
emailNotificationEnabled: boolean | null, 
/**
 * Whether to send a push notification when an incident occurs for this task
 * Will keep the existing value if null
 */
pushNotificationEnabled: boolean | null, 
/**
 * Whether to send a SMS notification when an incident occurs for this task
 * Will keep the existing value if null
 */
smsNotificationEnabled: boolean | null, };
