// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMetadata } from "./EntityMetadata";
import type { RequestHeaders } from "./RequestHeaders";

export type UpdateHttpMonitorCommand = { url: string, intervalSeconds: number, isActive: boolean, metadata: EntityMetadata, recoveryConfirmationThreshold: number, downtimeConfirmationThreshold: number, emailNotificationEnabled: boolean, pushNotificationEnabled: boolean, smsNotificationEnabled: boolean, requestHeaders: RequestHeaders, requestTimeoutMs: number, };
