// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, firstName: string, lastName: string, email: string, phoneNumber: string | null, phoneNumberVerified: boolean, };
